<a href="https://colab.research.google.com/github/Coder-twhjr/Hunting-Exoplanets-In-Space/blob/main/Hunting_Exoplanets_In_Space_Deploying_A_Prediction_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Hunting Exoplanets In Space - Deploying A Prediction Model

---

#### Loading The Datasets

In [2]:
import pandas as pd

exo_train_df = pd.read_csv('https://s3-student-datasets-bucket.whjr.online/whitehat-ds-datasets/kepler-exoplanets-dataset/exoTrain.csv')
exo_test_df = pd.read_csv('https://s3-student-datasets-bucket.whjr.online/whitehat-ds-datasets/kepler-exoplanets-dataset/exoTest.csv')

In [3]:
print(exo_train_df.shape)
exo_test_df.shape

(5087, 3198)


(570, 3198)

---

####The `value_counts()` Function

In [4]:
exo_test_df['LABEL'].value_counts()

1    565
2      5
Name: LABEL, dtype: int64

---

### Random Forest Classifier

---

####Importing `RandomForestClassifier`


In [5]:
from sklearn.ensemble import RandomForestClassifier

---

####Target & Feature Variables Separation


In [6]:
x_train = exo_train_df.iloc[:, 1:]
x_train.head()

FLUX.1   FLUX.2   FLUX.3   FLUX.4   FLUX.5   FLUX.6  FLUX.7   FLUX.8  \
0    93.85    83.81    20.10   -26.98   -39.56  -124.71 -135.18   -96.27   
1   -38.88   -33.83   -58.54   -40.09   -79.31   -72.81  -86.55   -85.33   
2   532.64   535.92   513.73   496.92   456.45   466.00  464.50   486.39   
3   326.52   347.39   302.35   298.13   317.74   312.70  322.33   311.31   
4 -1107.21 -1112.59 -1118.95 -1095.10 -1057.55 -1034.48 -998.34 -1022.71   

   FLUX.9  FLUX.10  ...  FLUX.3188  FLUX.3189  FLUX.3190  FLUX.3191  \
0  -79.89  -160.17  ...     -78.07    -102.15    -102.15      25.13   
1  -83.97   -73.38  ...      -3.28     -32.21     -32.21     -24.89   
2  436.56   484.39  ...     -71.69      13.31      13.31     -29.89   
3  312.42   323.33  ...       5.71      -3.73      -3.73      30.05   
4 -989.57  -970.88  ...    -594.37    -401.66    -401.66    -357.24   

   FLUX.3192  FLUX.3193  FLUX.3194  FLUX.3195  FLUX.3196  FLUX.3197  
0      48.57      92.54      39.32      61.42       5.08     -39.54  
1      -4.86       0.76     -11.70       6.46      16.00      19.93  
2     -20.88       5.06     -11.80     -28.91     -70.02     -96.67  
3      20.03     -12.67      -8.77     -17.31     -17.35      13.98  
4    -443.76    -438.54    -399.71    -384.65    -411.79    -510.54  

[5 rows x 3197 columns]

In [7]:
y_train = exo_train_df.iloc[:, 0] 
y_train.head()

0    2
1    2
2    2
3    2
4    2
Name: LABEL, dtype: int64

---

#### Fitting The Model


In [8]:
rf_clf = RandomForestClassifier(n_jobs=-1, n_estimators=50)

rf_clf.fit(x_train, y_train)

rf_clf.score(x_train, y_train)

0.9998034204835856

---

####Target & Feature Variables From Test Dataset

In [9]:
x_test = exo_test_df.iloc[:, 1:]
x_test.head()

FLUX.1   FLUX.2   FLUX.3   FLUX.4   FLUX.5   FLUX.6   FLUX.7   FLUX.8  \
0   119.88   100.21    86.46    48.68    46.12    39.39    18.57     6.98   
1  5736.59  5699.98  5717.16  5692.73  5663.83  5631.16  5626.39  5569.47   
2   844.48   817.49   770.07   675.01   605.52   499.45   440.77   362.95   
3  -826.00  -827.31  -846.12  -836.03  -745.50  -784.69  -791.22  -746.50   
4   -39.57   -15.88    -9.16    -6.37   -16.13   -24.05    -0.90   -45.20   

    FLUX.9  FLUX.10  ...  FLUX.3188  FLUX.3189  FLUX.3190  FLUX.3191  \
0     6.63   -21.97  ...      14.52      19.29      14.44      -1.62   
1  5550.44  5458.80  ...    -581.91    -984.09   -1230.89   -1600.45   
2   207.27   150.46  ...      17.82     -51.66     -48.29     -59.99   
3  -709.53  -679.56  ...     122.34      93.03      93.03      68.81   
4    -5.04    14.62  ...     -37.87     -61.85     -27.15     -21.18   

   FLUX.3192  FLUX.3193  FLUX.3194  FLUX.3195  FLUX.3196  FLUX.3197  
0      13.33      45.50      31.93      35.78     269.43      57.72  
1   -1824.53   -2061.17   -2265.98   -2366.19   -2294.86   -2034.72  
2     -82.10    -174.54     -95.23    -162.68     -36.79      30.63  
3       9.81      20.75      20.25    -120.81    -257.56    -215.41  
4     -33.76     -85.34     -81.46     -61.98     -69.34     -17.84  

[5 rows x 3197 columns]

In [10]:
y_test = exo_test_df.iloc[:, 0]
y_test.head()

0    2
1    2
2    2
3    2
4    2
Name: LABEL, dtype: int64

---

#### The `predict()` Function

In [11]:
y_predicted = rf_clf.predict(x_test)
y_predicted

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [12]:
type(y_predicted)

numpy.ndarray

In [13]:
y_predicted = pd.Series(y_predicted)
y_predicted.head()

0    1
1    1
2    1
3    1
4    1
dtype: int64

In [14]:
y_predicted.value_counts()

1    570
dtype: int64

---

####Multiples

In [15]:
import numpy as np
def m_multiples_of_n(n, m):
  multiples = np.arange(n, (n * m) + 1, n)
  print(multiples)

m_multiples_of_n(2, 3)
m_multiples_of_n(3, 4)

[2 4 6]
[ 3  6  9 12]


---

####Centered Penatognal Number

In [16]:
def centered_pentagonal_dots(num_pentagons):
  num = 1
  difference = 5
  num_pentagons_list = []
  while num_pentagons > 0:  
    num_pentagons_list.append(num)
    num = num + difference
    difference += 5
    num_pentagons -= 1
  # return num_pentagons_list
  return num_pentagons_list[-1]

print(centered_pentagonal_dots(4))
print(centered_pentagonal_dots(10))
print(centered_pentagonal_dots(21))

31
226
1051


---